apiVersion: v1
data:
  application-prod.properties: |2

    status.message=prod profile status check configmap

    eureka.client.serviceUrl.defaultZone = http://svc-discovery.default.svc.cluster.local:8011/eureka

    spring.datasource.url=jdbc:postgresql://postgresdb-stateful-0.postgres-headless-svc.default.svc.cluster.local:5432/learning
    spring.datasource.username=postgres
  application-prod1.properties: |2

    status.message=prod1 profile status check

    eureka.client.serviceUrl.defaultZone = http://10.244.0.10:8010/eureka
  application-prod2.properties: |2

    status.message=prod2 profile status check

    eureka.client.serviceUrl.defaultZone = http://svc-discovery.default.svc.cluster.local/eureka
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-26T10:44:21Z"
  name: college-configmap
  namespace: default
  resourceVersion: "272745"
  uid: 75025daa-d447-48ea-b650-1999172c32b7
